### ISSUE TITLE
Add a new gardening  area

### ISSUE THREAD

**Issue by sapphaos** [LeJardinDesSaisons/BioNotes#4]
As a market gardener
I want to add a new gardening area
So that I can manage them

### Add a new area
- Access to the parent area
- Adding begins
- Specify type
- Specify number
- Specify name
- Confirm the addition

---

### Todo
- [x] View : Create adding page and form component
- [x] View : Display where the area will be added
- [ ] Controller : Autocomplete the name with type + number
- [x] Model : Create Area and Type domain classes
- [x] Model : Get every type of areas
- [x] Model : Get an area's ancestors
- [x] Model : Add an area to the Storage

![jardins.png](https://images.zenhubusercontent.com/5c38c7a525bf9d709c50edae/04533922-a345-433d-bd6d-1175a2bda007)
![ajoutespace.png](https://images.zenhubusercontent.com/5c38c7a525bf9d709c50edae/16b35315-96fa-4994-829e-8868381d702e)
