### ISSUE TITLE
Edit an area

### ISSUE THREAD

**Issue by sapphaos** [LeJardinDesSaisons/BioNotes#5]
As a market gardener 
I want to edit an garden area 
So that I can modify wrong information 

### Edit an area
- Access to the parent area
- Select wanted area
- Access edition screen
- Rename area
- Change the number
- Change the type
- Confirm

---
### Todo
- [ ] View : Create edition page and form component
- [ ] View : Create the edition option on the area arborescence
- [ ] Controller : Autocomplete the name with type + number
- [ ] Controller : Activate the edition option on the area arborescence
- [ ] Model : Edit an area

![editerouarchiver.png](https://images.zenhubusercontent.com/5c38c7a525bf9d709c50edae/29b8c17c-6871-4069-b7fe-a02dc0a1fc27)
![edition.png](https://images.zenhubusercontent.com/5c38c7a525bf9d709c50edae/b3ccc943-3a19-4db5-b355-71320229b8f4)
